apiVersion: ops.kubedb.com/v1alpha1
kind: MySQLOpsRequest
metadata:
  name: myopsreq-standalone
  namespace: demo
spec:
  type: Upgrade
  databaseRef:
    name: my-standalone
  upgrade:
    targetVersion: "8.0.20"