apiVersion: ops.kubedb.com/v1alpha1
kind: MongoDBOpsRequest
metadata:
  name: horizontal
  namespace: demo
spec:
  type: HorizontalScaling
  databaseRef:
    name: mg-sh
  horizontalScaling:
    shard:
      shards: 3
      replicas: 4
  apply: IfReady