apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mg-issuer
  namespace: demo
spec:
  ca:
    secretName: mongo-ca


# To create the mongo-ca secret:
# (1) openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ./ca.key -out ./ca.crt -subj "/CN=mongo/O=kubedb"
# (2) kubectl create secret tls mongo-ca \
#      --cert=ca.crt \
#      --key=ca.key \
#      --namespace=demo
