apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: global
  namespace: kubeops
spec:
  # numberOfClusters: 2
  clusterSets:
    - global

---

apiVersion: work.open-cluster-management.io/v1alpha1
kind: ManifestWorkReplicaSet
metadata:
  name: operators
  namespace: kubeops
spec:
  placementRefs:
    - name: global
  manifestWorkTemplate:
    # deleteOption:
    #   propagationPolicy: SelectivelyOrphan
    #   selectivelyOrphans:
    #     orphaningRules:
    #       - group: ''
    #         name: ocm-ns
    #         namespace: ''
    #         resource: Namespace
    # manifestConfigs:
    #   - feedbackRules:
    #       - jsonPaths:
    #           - name: lastScheduleTime
    #             path: .status.lastScheduleTime
    #           - name: lastSuccessfulTime
    #             path: .status.lastSuccessfulTime
    #         type: JSONPaths
    #     resourceIdentifier:
    #       group: batch
    #       name: sync-cronjob
    #       namespace: ocm-ns
    #       resource: cronjobs
    workload:
      manifests:
        - kind: Namespace
          apiVersion: v1
          metadata:
            name: kubeops

        - apiVersion: source.toolkit.fluxcd.io/v1beta2
          kind: HelmRepository
          metadata:
            name: prometheus-community
            namespace: kubeops
          spec:
            interval: 30m
            url: https://prometheus-community.github.io/helm-charts

        - apiVersion: helm.toolkit.fluxcd.io/v2beta1
          kind: HelmRelease
          metadata:
            name: kube-prometheus-stack
            namespace: kubeops
          spec:
            interval: 60m
            releaseName: kube-prometheus-stack
            targetNamespace: monitoring
            storageNamespace: monitoring
            install:
              createNamespace: true
            chart:
              spec:
                chart: kube-prometheus-stack
                # version: "^5.x"
                sourceRef:
                  kind: HelmRepository
                  name: prometheus-community
                  namespace: kubeops

        - apiVersion: source.toolkit.fluxcd.io/v1beta2
          kind: HelmRepository
          metadata:
            name: appscode
            namespace: kubeops
          spec:
            interval: 30m
            url: https://charts.appscode.com/stable/

        - apiVersion: helm.toolkit.fluxcd.io/v2beta1
          kind: HelmRelease
          metadata:
            name: license-proxyserver
            namespace: kubeops
          spec:
            interval: 60m
            releaseName: license-proxyserver
            targetNamespace: kubeops
            storageNamespace: kubeops
            install:
              createNamespace: true
            chart:
              spec:
                chart: license-proxyserver
                version: "v2023.03.23"
                sourceRef:
                  kind: HelmRepository
                  name: appscode
                  namespace: kubeops
            values:
              platform:
                baseURL: https://api.byte.builders/
                token: 49cd70468453c33a08ac805f45d64b45b443bce9

        - apiVersion: helm.toolkit.fluxcd.io/v2beta1
          kind: HelmRelease
          metadata:
            name: kubedb
            namespace: kubeops
          spec:
            interval: 5m
            timeout: 30m
            releaseName: kubedb
            targetNamespace: kubedb
            storageNamespace: kubedb
            chart:
              spec:
                chart: kubedb
                version: "v2023.06.13-rc.0"
                sourceRef:
                  kind: HelmRepository
                  name: appscode
                  namespace: kubeops
            install:
              createNamespace: true
              crds: CreateReplace
              remediation:
                retries: -1
            upgrade:
              crds: CreateReplace
              remediation:
                retries: -1
            values:
              kubedb-provisioner:
                enabled: true
              kubedb-catalog:
                enabled: true
              kubedb-ops-manager:
                enabled: true
              kubedb-autoscaler:
                enabled: false
              kubedb-schema-manager:
                enabled: false
              kubedb-dashboard:
                enabled: false
                
        - apiVersion: helm.toolkit.fluxcd.io/v2beta1
          kind: HelmRelease
          metadata:
            name: stash
            namespace: kubeops
          spec:
            interval: 5m
            timeout: 30m
            releaseName: stash
            targetNamespace: stash
            storageNamespace: stash
            chart:
              spec:
                chart: stash
                version: "v2023.05.31"
                sourceRef:
                  kind: HelmRepository
                  name: appscode
                  namespace: kubeops
            install:
              createNamespace: true
              crds: CreateReplace
              remediation:
                retries: -1
            upgrade:
              crds: CreateReplace
              remediation:
                retries: -1
            values:
              features:
                enterprise: true
