apiVersion: kubedb.com/v1alpha2
kind: MariaDB
metadata:
  name: mariadb-server
  namespace: dev
spec:
  version: "10.5.8"
  storageType: Durable
  replicas: 3
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 200Mi
  allowedSchemas:
    namespaces:
      from: Selector
      selector:
        matchLabels:
          app: schemaManager
  terminationPolicy: WipeOut
