apiVersion: kubedb.com/v1alpha2
kind: ProxySQL
metadata:
  name: proxy-server
  namespace: demo
spec:
  version: "2.3.2-debian"
  replicas: 3
  mode: GroupReplication
  backend:
    ref:
      apiGroup: "kubedb.com"
      kind: MySQL
      name: mysql-server
    replicas: 3
  syncUsers: false
  initConfig:
    mysqlUsers: 
      - username: user1
        active: 1
        default_hostgroup: 2
   adminVariables:
     refresh_interval: 2050
     cluster_mysql_users_diffs_before_sync: 2
   configSecret:
     name: my-config-secret
  terminationPolicy: WipeOut
  healthChecker:
    failureThreshold: 3
