apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: rs
  namespace: demo
spec:
  version: "percona-4.4.10"
  replicaSet:
    name: "replicaset"
  podTemplate:
    spec:
      resources:
        requests:
          cpu: "400m"
          memory: "400Mi"
  replicas: 3
  storageEngine: inMemory
  storageType: Ephemeral
  sslMode: requireSSL
  tls:
    issuerRef:
      apiGroup: "cert-manager.io"
      kind: Issuer
      name: mongo-ca-issuer
  clusterAuthMode: x509
  arbiter:
    podTemplate:
      spec:
        resources:
          requests:
            cpu: "200m"
            memory: "200Mi"
  hidden:
    podTemplate:
      spec:
        resources:
          requests:
            cpu: "300m"
            memory: "300Mi"
    replicas: 2
    storage:
      storageClassName: "standard"
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  terminationPolicy: WipeOut