apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: db-pg
  namespace: db
spec:
  version: "13.2"
  allowedSchemas:
    namespaces:
      from: Selector
      selector:
        matchLabels:
         kubernetes.io/metadata.name: dev
    selector:
      matchLabels:
        schema.kubedb.com/instance_name: schema
  authSecret:
    name: "pg-custom-auth"
  replicas: 3
  standbyMode: Hot
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut

