apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: db
type: Opaque
data:
  AWS_ACCESS_KEY_ID: <YOUR AWS ACCESS KEY HERE>
  AWS_SECRET_ACCESS_KEY: <YOUR AWS SECRET KEY HERE>
  RESTIC_PASSWORD: <RESTIC PASSWORD>

