apiVersion: stash.appscode.com/v1beta1
kind: BackupSession
metadata:
  name: trigger-mg-rs-backup
  namespace: demo
  labels:
    stash.appscode.com/invoker-name: mg-rs-backup
    stash.appscode.com/invoker-type: BackupConfiguration
spec:
  invoker:
    apiGroup: stash.appscode.com
    kind: BackupConfiguration
    name: mg-rs-backup