apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: mg-rs-restore
  namespace: demo
  labels:
    kubedb.com/kind: MongoDB
spec:
  task:
    name: mongodb-restore-4.2.3-v5
  repository:
    name: gcs-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: mg-rs-tls
  rules:
  - snapshots: [latest]