apiVersion: ops.kubedb.com/v1alpha1
kind: MariaDBOpsRequest
metadata:
  name: md-upscale
  namespace: demo
spec:
  type: HorizontalScaling  
  databaseRef:
    name: sample-mariadb
  horizontalScaling:
    member: 5
