apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: restore-pg
  namespace: demo
spec:
  init:
    archiver:
      recoveryTimestamp: "2023-08-31T07:15:21.938827Z"
      fullDBRestore:
        repository:
          name: demo-pg-repository
          namespace: demo
      manifestRestore:
        encryptionSecret:
          name: encrypt-secret
          namespace: demo
        repository:
          name: demo-pg-manifest
          namespace: demo
  version: "13.6-bullseye"
  replicas: 3
  standbyMode: Hot
  storageType: Durable
  storage:
    storageClassName: "longhorn"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut
