apiVersion: work.open-cluster-management.io/v1alpha1
kind: ManifestWorkReplicaSet
metadata:
  name: db
  namespace: app2
spec:
  placementRefs:
    - name: app2
  manifestWorkTemplate:
    # deleteOption:
    #   propagationPolicy: SelectivelyOrphan
    #   selectivelyOrphans:
    #     orphaningRules:
    #       - group: ''
    #         name: ocm-ns
    #         namespace: ''
    #         resource: Namespace
    # manifestConfigs:
    #   - feedbackRules:
    #       - jsonPaths:
    #           - name: lastScheduleTime
    #             path: .status.lastScheduleTime
    #           - name: lastSuccessfulTime
    #             path: .status.lastSuccessfulTime
    #         type: JSONPaths
    #     resourceIdentifier:
    #       group: batch
    #       name: sync-cronjob
    #       namespace: ocm-ns
    #       resource: cronjobs
    workload:
      manifests:
        - kind: Namespace
          apiVersion: v1
          metadata:
            name: app2

        - apiVersion: kubedb.com/v1alpha2
          kind: MySQL
          metadata:
            name: mysql-quickstart
            namespace: app2
          spec:
            version: "8.0.29"
            storageType: Durable
            storage:
              storageClassName: "standard"
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
            terminationPolicy: Delete
