apiVersion: ops.kubedb.com/v1alpha1
kind: MongoDBOpsRequest
metadata:
  name: horizontal
  namespace: demo
spec:
  type: HorizontalScaling
  databaseRef:
    name: sh
  horizontalScaling:
    shard:
      shards: 3
      replicas: 2
    hidden:
      replicas: 1
    configServer:
      replicas: 2
    mongos:
      replicas: 3