apiVersion: kubevault.com/v1alpha1
kind: VaultServer
metadata:
  name: vault
  namespace: demo
spec:
  version: 1.8.2
  replicas: 3
  allowedSecretEngines:
    namespaces:
      from: All
    secretEngines:
      - mongodb
  unsealer:
    secretShares: 5
    secretThreshold: 3
    mode:
      kubernetesSecret:
        secretName: vault-keys
  backend:
    raft:
      path: "/vault/data"
      storage:
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi
  authMethods:
    - type: kubernetes
      path: kubernetes
  monitor:
    agent: prometheus.io
    prometheus:
      exporter:
        resources: {}
  terminationPolicy: WipeOut

# apiVersion: v1
# kind: Namespace
# metadata:
#   labels:
#     kubernetes.io/metadata.name: dev
#   name: dev

# apiVersion: v1
# kind: Namespace
# metadata:
#   labels:
#     kubernetes.io/metadata.name: db
#   name: db

# apiVersion: v1
# kind: Namespace
# metadata:
#   labels:
#     kubernetes.io/metadata.name: demo
#   name: demo