{
 "title": "Kubernetes Deployment Dashboard by Panopticon",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Deployment", "query": { "query": "label_values(deployment)" } },
   { "name": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Spec Replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\"^$Deployment$\", namespace=~\"^$Namespace\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Status Replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=~\"^$Deployment$\", namespace=~\"^$Namespace\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Ready Replicas(%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{deployment=~\"^$Deployment$\", namespace=~\"^$Namespace\"} / kube_deployment_spec_replicas{deployment=~\"^$Deployment$\", namespace=~\"^$Namespace\"} * 100",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Available Replicas(%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=~\"^$Deployment$\", namespace=~\"^$Namespace\"} / kube_deployment_spec_replicas{deployment=~\"^$Deployment$\", namespace=~\"^$Namespace\"} * 100",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Paused Replicas(%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_paused{deployment=~\"^$Deployment$\", namespace=~\"^$Namespace\"} / kube_deployment_spec_replicas{deployment=~\"^$Deployment$\", namespace=~\"^$Namespace\"} * 100",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Updated Replicas(%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_updated{deployment=~\"^$Deployment$\", namespace=~\"^$Namespace\"} / kube_deployment_spec_replicas{deployment=~\"^$Deployment$\", namespace=~\"^$Namespace\"} * 100",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}