{
 "title": "KubeDB MongoDB Dashboard by Panopticon",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "MongoDB", "query": { "query": "label_values(mongodb)" } },
   { "name": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "MongoDB Mode",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_mongodb_mode{mongodb=~\"^$MongoDB\", namespace=~\"^$Namespace\"} == 1",
     "legendFormat": "{{mongodb}}-[{{mode}}]"
    }
   ]
  },
  {
   "title": "Replicas ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_mongodb_replicas{mongodb=~\"^$MongoDB\", namespace=~\"^$Namespace\"}",
     "legendFormat": "{{mongodb}}"
    }
   ]
  },
  {
   "title": "Current Phase",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_mongodb_status_phase{mongodb=~\"^$MongoDB\", namespace=~\"^$Namespace\"} == 1",
     "legendFormat": "{{mongodb}} [{{phase}}]"
    }
   ]
  },
  {
   "title": "CPU Request(core)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "kubedb_mongodb_resource_request_cpu{mongodb=~\"^$MongoDB\", namespace=~\"^$Namespace\"}",
     "legendFormat": "{{mongodb}}"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubedb_mongodb_resource_request_memory{mongodb=~\"^$MongoDB\", namespace=~\"^$Namespace\"}",
     "legendFormat": "{{mongodb}}"
    }
   ]
  },
  {
   "title": "Storage Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubedb_mongodb_resource_request_storage{mongodb=~\"^$MongoDB\", namespace=~\"^$Namespace\"}",
     "legendFormat": "{{mongodb}}"
    }
   ]
  },
  {
   "title": "CPU Limit(core)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kubedb_mongodb_resource_limit_cpu{mongodb=~\"^$MongoDB\", namespace=~\"^$Namespace\"}",
     "legendFormat": "{{mongodb}}"
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubedb_mongodb_resource_limit_memory{mongodb=~\"^$MongoDB\", namespace=~\"^$Namespace\"}",
     "legendFormat": "{{mongodb}}"
    }
   ]
  },
  {
   "title": "Storage Limit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubedb_mongodb_resource_limit_storage{mongodb=~\"^$MongoDB\", namespace=~\"^$Namespace\"}",
     "legendFormat": "{{mongodb}}"
    }
   ]
  }
 ]
}