apiVersion: stash.appscode.com/v1beta1
kind: BackupSession
metadata:
  name: rd-backup-trigger
  namespace: demo
spec:
  invoker:
    apiGroup: stash.appscode.com
    kind: BackupConfiguration
    name: sample-redis-backup