apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: s3-repo
  namespace: demo
spec:
  backend:
    s3:
      endpoint: https://us-east-1.linodeobjects.com # use server URL for s3 compatible other storage service
      bucket: stash-backup
      region: us-east-1
      prefix: redis2
    storageSecretName: s3-secret
