apiVersion: ops.kubedb.com/v1alpha1
kind: MariaDBOpsRequest
metadata:
  name: volume-expansion
  namespace: demo
spec:
  type: VolumeExpansion
  databaseRef:
    name: sample-mariadb
  volumeExpansion:   
    mode: Online
    mariadb: 2Gi
