apiVersion: stash.appscode.com/v1beta1
kind: BackupSession
metadata:
  name: sample-mariadb-backup-now
  namespace: demo
spec:
  invoker:
    apiGroup: stash.appscode.com
    kind: BackupConfiguration
    name: sample-mariadb-backup
