apiVersion: ops.kubedb.com/v1alpha1
kind: MySQLOpsRequest
metadata:
  name: mysql-add-tls
  namespace: demo
spec:
  type: ReconfigureTLS
  databaseRef:
    name: mysql
  tls:
    issuerRef:
      name: mysql-issuer
      kind: Issuer
      apiGroup: "cert-manager.io"
    certificates:
      - alias: client
        subject:
          organizations:
            - mysql
          organizationalUnits:
            - client
    requireSSL: true