apiVersion: ops.kubedb.com/v1alpha1
kind: MySQLOpsRequest
metadata:
  name: tls-remove-standalone
  namespace: demo
spec:
  type: ReconfigureTLS
  databaseRef:
    name: mysql-read
  tls:
    remove: true